# Version: v1.1
name: Rust CI (AVR)

on:
  push:
    branches: [ "main", "motors-control", "rover-controller", "feature/encoders", "feature/proximity" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ATmega2560
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install AVR toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-avr avr-libc

    - name: Configure Rust Nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src

    - name: Build library
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --target avr-none -Z build-std=core

    - name: Build example - control_6_motors_l298n
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example control_6_motors_l298n --target avr-none -Z build-std=core

    - name: Build example - test_controller
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_controller --target avr-none -Z build-std=core

    - name: Build example - test_encoders
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_encoders --target avr-none -Z build-std=core

    - name: Build example - test_proximity
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_proximity --target avr-none -Z build-std=core

    - name: Build example - test_bts7960
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_bts7960 --target avr-none -Z build-std=core

    - name: Build example - test_servo
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_servo --target avr-none -Z build-std=core

    - name: Build example - test_l298n
      run: |
        RUSTFLAGS="-C target-cpu=atmega2560" cargo build --example test_l298n --target avr-none -Z build-std=core
